version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db      
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    restart: always
      
  back:
    build: .
    depends_on:
      - postgres  
    ports:
    - '3000:3000'
    env_file:
      - .env.docker     

volumes:
  postgres-data: